### ISSUE TITLE
Code from example does not work

### ISSUE THREAD

**Issue by ivanstepanovftw** [tiagocoutinho/linuxpy#21]
`/p/i/gaze/capture.py`
```py
from linuxpy.video.device import Device


if __name__ == '__main__':
    with Device.from_id(1) as cam:
        print(f"{cam=}")
        for i, frame in enumerate(cam):
            print(f"frame #{i}: {len(frame)} bytes")
            if i > 9:
                break
```
Outputs
```
/usr/bin/python3.12 /p/i/gaze/capture.py 
cam=<Device name=/dev/video1, closed=False>
Traceback (most recent call last):
  File "/p/i/gaze/capture.py", line 7, in <module>
    for i, frame in enumerate(cam):
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 749, in __iter__
    with VideoCapture(self) as stream:
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 1407, in __enter__
    self.open()
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 1435, in open
    self.buffer.open()
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 1537, in open
    buffers = self.buffer_manager.create_buffers(Memory.MMAP)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 1282, in create_buffers
    self.buffers = self.device.create_buffers(self.type, memory, self.size)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 774, in create_buffers
    return create_buffers(self.fileno(), buffer_type, memory, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 719, in create_buffers
    request_buffers(fd, buffer_type, memory, count)
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/video/device.py", line 459, in request_buffers
    ioctl(fd, IOC.REQBUFS, req)
  File "/home/i/.local/lib/python3.12/site-packages/linuxpy/ioctl.py", line 67, in ioctl
    fcntl.ioctl(fd, request, *args)
OSError: [Errno 22] Invalid argument

Process finished with exit code 1
```

Note I have `/dev/video0` for infrared and `/dev/video1` for RGB. Maybe I am doing something wrong?

**Comment by ivanstepanovftw** [comment]
No, no, no, everything is fine when I use `/dev/video0`. My bad.
```
from io import BytesIO

from linuxpy.video.device import Device
import matplotlib.pyplot as plt
from PIL import Image

if __name__ == '__main__':
    with Device.from_id(0) as cam:
        print(f"{cam=}")
        for i, frame in enumerate(cam):
            print(f"frame #{i}: {len(frame)} bytes")
            image = Image.open(BytesIO(bytes(frame)))
            plt.imshow(image)
            plt.show()
            if i > 9:
                break
```

**Comment by Dipankar1997161** [comment]
> BTW I have 5 /dev/video* devices, not sure why.

try using iter_video_capture_devices function present in llinuxpy.video.device and check the results.
this saves you from using 'from_id'

**Comment by tiagocoutinho** [comment]
Can I close the issue?

**Comment by ivanstepanovftw** [comment]
Many thanks for this beautiful library, will recommend to everyone

**Comment by ivanstepanovftw** [comment]
Strange, when my camera is occupied, it still shows that camera is closed.
```python
from linuxpy.video.device import Device, iter_video_capture_devices
devices = list(iter_video_capture_devices())
print(f"{devices=}")
```
```
devices=[<Device name=/dev/video2, closed=True>, <Device name=/dev/video0, closed=True>]
```
